spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  key: GJDSKLAGJDLSA-WGJEKWLGJEWKAG-GEWJLGEJLSKAGJ
